# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Atakan-Emre"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/dev_atakan"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://twitter.com/dev_atakan"

[social.params]
icon = "brand-instagram"


